### PR TITLE
skillSelection

### PR DESCRIPTION
**Pull request by jlstanford**

### CODE REVIEW

**Comment by doctor-g** [comment]
This branch doesn't compile, unless I'm doing something wrong. There are two kinds of errors: some that deal with conflicts in source files that have changed, and some related to the language level. The latter category may have to do with the IML file alterations, which make me a little nervous.

**Comment by jlstanford** [comment]
Really? hmm it worked on my machine so I figured it was fine. Let me look at it. Should I just keep the language level under 8?

**Comment by jtmcginnis** [comment]
My machine is also running the code just fine. I have yet to work with the IML and the language level is only an issue with empty brackets and lambda expressions, which can be easily changed.

**Comment by doctor-g** [comment]
@jlstanford no, language level 8 is right. I'm confused as to why it was ever set to anything else. Looking at the history for compiler.xml, it looks like it goes back to an early commit. Your change, to level 8, is appropriate. I wonder how that didn't get updated sooner?

@jtmcginnis I cannot think of a good reason to avoid diamond operator or lambdas, since we're in Java 8 with FX anyway. Next iteration may show us something else, but I'd rather just keep the code in 8 for now.

**Comment by doctor-g** [comment]
If you're seeing the code as compiling, then you have something wrong with your settings or you are doing something wrong. Travis tells us that it's not compiling, and it wouldn't lie: it's checking out the project cleanly from github: https://travis-ci.org/spring-studio-2016/storygame/builds/107007692

A possible culprit is that you have files that you forgot to commit. Check the Version Control tab in IntelliJ IDEA to see if you have files that are not staged for commit. IDEA would still be compiling these, since they're in your local workspace, but they would not be pushed to github since they were never staged.

**Comment by jlstanford** [comment]
Okay, Ill check that out.

**Comment by doctor-g** [comment]
FYI: I just spent half an hour or so researching IDEA settings and fiddling with the relevant IDEA files. The commit I just pushed to master should have this fixed up in a clean way. Please try using the IDEA files from that commit (compiler.xml, misc.xml, and storygame.iml) and see if that doesn't fix the language level problems once and for all.

**Pull request closed without merging**
