### PR TITLE
Organized user interface

### PR DESCRIPTION
**Pull request by jtmcginnis**
Removed errors.
Separate views are now accessed from the master interface

### CODE REVIEW

**Comment by doctor-g** [comment]
Looks like there's three commits here, two of which are broken, all with identical messages, none of which are following the Git conventions. @jtmcginnis, let's get together tomorrow and I'll show you how to clean up the history on this branch before we merge it in.

In related github weirdness, why is my comment showing up in the middle of the commit timeline? I wonder if @jalohse or @zbruh or somebody with more team github experience would know. I would expect the message to show up in a more sensible chronological order. (For that matter, I would expect it to show up right after I enter it, rather than having to wait and reload this page.)

**Comment by jtmcginnis** [comment]
@doctor-g Helping me with GitHub will be much appreciated. Last semester, GitHub was used to awful effect in my group project so it tends to make me a touch flustered on approach.

**Comment by pacorain** [comment]
@doctor-g My best guess would be a time zone issue, because looking at the times of the commits and your comment, they _are_ in chronological order.  I changed my clock time to an hour forward for a [hello-world commit](https://github.com/zbruh/hello-world/blob/master/commit-to-the-future.txt) and now GitHub just says it was committed "just now", and I assume will do so until after about 45 minutes from now.

Also yes, having to refresh the page to make this edit to my comment was a little annoying.

**Comment by doctor-g** [comment]
Poking around the web a bit, such as [this SO question](http://webapps.stackexchange.com/questions/49956/what-time-zone-are-the-main-github-servers-located-in), it makes me wonder if it can infer anything from your profile location. @jtmcginnis, what's your location setting? Mine is "Muncie, IN, USA". It could also be related to local time settings, as @zbruh mentions, but I assume we're all using local time on our development machines.

**Pull request merged**
