### PR TITLE
Player update

### PR DESCRIPTION
**Pull request by jalohse**
This lets the PlayerView update once the player is updated. The Player constructor is now simplified.

### CODE REVIEW

**Comment by doctor-g** [comment]
It looks like Player.position is never used and can be removed. 

The "skill" concept should use something more robust than String. An enum would be an easy swap.

For any of those fields that don't change, like player color, I would mark them final.

The `getTotalPoints` is redundant with having `totalPoints` exposed as a public final; I'd get rid of the former.

Similarly, if `skills` is exposed as a public final `RList` then you do not need an `addSkill` method: it's redundant with the call `player.skills.add(...)`. (The bigger idea here is that there should be only one way to do the operation, not two; you can pick the one you prefer, but when using react, I usually just go with the public final route, for brevity of code.... and then occasionally regret it, but that's the nature of refactoring.)

`addPoint` is similar---don't need it.

It looks like `getSkillString` is preparing the skill list for display in the UI, but that's a UI concern: let the `PlayerView` (or whatever it ends up being called) handle that.

**Comment by doctor-g** [comment]
Also, if you like, we can work on cleaning the commit history. I like to work in lots of little commits on a feature branch, but then collapse these into feature-oriented commits---usually just one or two---before merging back into master. You know where to find me.

**Comment by jalohse** [comment]
@doctor-g The position was something that was already in the Player class that was already in master. The Skill enum has yet to be put in master as well and I was waiting for that work to be finished. I can remove those methods and move that string to the UI.

**Comment by doctor-g** [comment]
It looks like `position` is a private field that is never read, though: I don't think it does anything, unless I'm missing something. If it's dead code, we can just cut it out.
For the skill, I wouldn't worry about someone else working on it: it's three lines of code. I would just throw it into master if this is working, and others can merge with it if they see some other constraints that we haven't here.

**Pull request merged**
